import sampleImage from '../assets/products/bras/bandeau/Black.png';
import sampleImage2 from '../assets/products/bras/cups/blue.png';

const BANDEAU = [
	{
		sku: '1BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'tops',
		price: 38,
		color: 'Black',
		image: sampleImage,
		featured: true,
		bestseller: false,
		stock: 100,
		sale: {
			onSale: true,
			discount: 22,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
	{
		sku: '10BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'tops',
		price: 38,
		color: 'Black',
		image: sampleImage,
		featured: false,
		bestseller: true,
		stock: 100,
		sale: {
			onSale: false,
			discount: 0,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
	{
		sku: '2BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'bottoms',
		price: 38,
		color: 'Black',
		image: sampleImage2,
		featured: false,
		bestseller: false,
		stock: 100,
		sale: {
			onSale: false,
			discount: 0,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
	{
		sku: '3BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'bottoms',
		price: 38,
		color: 'Black',
		image: sampleImage,
		featured: true,
		bestseller: false,
		stock: 100,
		sale: {
			onSale: false,
			discount: 0,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
	{
		sku: '4BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'tops',
		price: 38,
		color: 'Black',
		image: sampleImage,
		featured: false,
		bestseller: false,
		stock: 100,
		sale: {
			onSale: false,
			discount: 0,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
	{
		sku: '5BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'tops',
		price: 38,
		color: 'Black',
		image: sampleImage,
		featured: false,
		bestseller: true,
		stock: 100,
		sale: {
			onSale: false,
			discount: 0,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
	{
		sku: '6BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'tops',
		price: 38,
		color: 'Black',
		image: sampleImage,
		featured: false,
		bestseller: false,
		stock: 100,
		sale: {
			onSale: false,
			discount: 0,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
	{
		sku: '7BAND',
		title: 'Bandeau bikini top',
		description: 'Lorem Ipsum',
		category: 'tops',
		price: 38,
		color: 'Black',
		image: sampleImage,
		featured: false,
		bestseller: false,
		stock: 100,
		sale: {
			onSale: false,
			discount: 0,
		},
		options: {
			colors: [
				{
					sku: 'bla',
					value: 'Black',
					// image: ,
					// swatchURL: colorSwatches.black,
				},
				{
					sku: 'blac',
					value: 'Black circles',
					// image: ,
					// swatchURL: colorSwatches.blackCircles,
				},
				{
					sku: 'blaf',
					value: 'Black flowers',
					// image: ,
					// swatchURL: colorSwatches.blackFlower,
				},
				{
					sku: 'blu',
					value: 'Blue',
					// image: ,
					// swatchURL: colorSwatches.blue,
				},
				{
					sku: 'bluo',
					value: 'Blue Ocean',
					// image: ,
					// swatchURL: colorSwatches.blueOcean,
				},
				{
					sku: 'oraw',
					value: 'Orange Watercolor',
					// image: ,
					// swatchURL: colorSwatches.orangeWatercolor,
				},
				{
					sku: 'red',
					value: 'Red',
					// image: ,
					// swatchURL: colorSwatches.red,
				},
				{
					sku: 'tur',
					value: 'Turquoise',
					// image: ,
					// swatchURL: colorSwatches.turquoise,
				},
				{
					sku: 'turs',
					value: 'Turquoise Stripes',
					// image: ,
					// swatchURL: colorSwatches.turquoiseStripe,
				},
				{
					sku: 'whi',
					value: 'White',
					// image: ,
					// swatchURL: colorSwatches.white,
				},
				{
					sku: 'whid',
					value: 'White Dots',
					// image: ,
					// swatchURL: colorSwatches.whiteDots,
				},
				{
					sku: 'whios',
					value: 'White Orange Splash',
					// image: ,
					// swatchURL: colorSwatches.whiteOrangeSplash,
				},
				{
					sku: 'yel',
					value: 'Yellow',
					// image: ,
					// swatchURL: colorSwatches.yellow,
				},
			],
		},
	},
];

export default BANDEAU;
